name: Build

on: 
  push:
  release:
    types: [created]

jobs:
  build_lin:
    name: Build on Linux
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Download X-Plane SDK
      uses: carlosperate/download-file-action@v1.0.3
      with:
        file-url: http://developer.x-plane.com/wp-content/plugins/code-sample-generation/sample_templates/XPSDK303.zip
        file-name: SDK.zip
        location: ./lib
        
    - name: Uncompress X-Plane SDK
      run: cd lib && unzip SDK && cd ..

    - name: Install Boost
      run: brew install boost
    
    - name: Build
      run: |
        cmake -B build -DXSDK_DIR=lib/SDK
        cmake --build build
        cmake --install build --prefix dist
        
    - name: Upload
      if: github.event_name == 'release'
      uses: actions/upload-artifact@v2
      with:
        name: lin_x64
        path: dist/XSharedCockpit/lin_x64/XSharedCockpit.xpl
      
  build_win:
    name: Build on Windows
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Download X-Plane SDK
      uses: carlosperate/download-file-action@v1.0.3
      with:
        file-url: http://developer.x-plane.com/wp-content/plugins/code-sample-generation/sample_templates/XPSDK303.zip
        file-name: SDK.zip
        location: ./lib
        
    - name: Uncompress X-Plane SDK
      run: cd lib && unzip SDK && cd ..
    
    - name: Build
      shell: bash
      run: |
        cmake -B build -DXSDK_DIR=lib/SDK -DBOOST_ROOT=$BOOST_ROOT_1_72_0 -G "MinGW Makefiles" -DCMAKE_MAKE_PROGRAM=mingw32-make
        cmake --build build
        cmake --install build --prefix dist
        
    - name: Upload
      if: github.event_name == 'release'
      uses: actions/upload-artifact@v2
      with:
        name: win_x64
        path: dist/XSharedCockpit/win_x64/XSharedCockpit.xpl
        
  build_mac:
    name: Build on macOS
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Download X-Plane SDK
      uses: carlosperate/download-file-action@v1.0.3
      with:
        file-url: http://developer.x-plane.com/wp-content/plugins/code-sample-generation/sample_templates/XPSDK303.zip
        file-name: SDK.zip
        location: ./lib
        
    - name: Uncompress X-Plane SDK
      run: cd lib && unzip SDK && cd ..
        
    - name: Install Boost
      run: brew install boost
    
    - name: Build
      run: |
        cmake -B build -DXSDK_DIR=lib/SDK
        cmake --build build
        cmake --install build --prefix dist
        
    - name: Upload
      if: github.event_name == 'release'
      uses: actions/upload-artifact@v2
      with:
        name: mac_x64
        path: dist/XSharedCockpit/mac_x64/XSharedCockpit.xpl
        
  package:
    name: Package the Plugin
    if: github.event_name == 'release'
    needs: [build_lin, build_win, build_mac]
    runs-on: ubuntu-latest
    
    steps:
    - name: Download plugins
      uses: actions/download-artifact@v2
      with:
        path: XSharedCockpit
        
    - name: Package
      run: zip -r XSharedCockpit XSharedCockpit
      
    - name: Upload
      uses: AButler/upload-release-assets@v2.0
      with:
        files: 'XSharedCockpit.zip'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
